# This yaml file is used by Google Cloud Container Builder to build the
# microservices in parallel and push them to Google Container Registry.
steps:
- id: compile
  name: gcr.io/cloud-builders/go:alpine
  env: 
  - "PROJECT_ROOT=github.com/SingularityInteractive/cohesiv"
  - "CGO_ENABLED=0"
  - "GOOS=linux"
  - "GOARCH=amd64"
  entrypoint: /bin/ash # we need this for the shell substitution below
  args:
  - '-c'
  - >
    go.ash install -v \
      -a -tags netgo \
      -ldflags="-w -X github.com/SingularityInteractive/cohesiv/version.version=$(git describe --always --dirty)" \
        ./api \
        ./tagdirectory
- name: gcr.io/cloud-builders/docker
  waitFor: ['compile']
  args: ['build', '-f=Dockerfile.api', '-t=gcr.io/$PROJECT_ID/api:$REVISION_ID', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-f=Dockerfile.tagdirectory', '-t=gcr.io/$PROJECT_ID/tagdirectory:$REVISION_ID', '.']
  waitFor: ['compile']
images:
  - 'gcr.io/$PROJECT_ID/api:$REVISION_ID'
  - 'gcr.io/$PROJECT_ID/tagdirectory:$REVISION_ID'
