---
clients:
 -
  name: cohesiv
  develop:
  staging:
  production:
 -
  name: mypds
  develop:
    spec:
      template:
        spec:
          containers:
          -
            name: mypds
            image: "750213922035.dkr.ecr.us-east-1.amazonaws.com/singularity/mypds:latest"
            env:
            -
              name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: cohesiv-secrets
                  key: develop-db-connection-string
  staging:
    spec:
      template:
        spec:
          containers:
          -
            name: mypds
            image: "750213922035.dkr.ecr.us-east-1.amazonaws.com/singularity/mypds:latest"
            env:
            -
              name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mypds-secrets
                  key: staging-db-connection-string
  production:
    spec:
      revisionHistoryLimit: 5
      replicas: 3
      template:
        spec:
          containers:
          -
            name: mypds
            image: "750213922035.dkr.ecr.us-east-1.amazonaws.com/singularity/mypds:master"
            env:
            -
              name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mypds-secrets
                  key: production-db-connection-string

 -
  name: asu
  develop:
  staging:
  production:
  
