---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  revisionHistoryLimit: 5
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: api
    spec:
      # [START volumes]
      # [START containers]
      containers:
      - name: api
        image: "750213922035.dkr.ecr.us-east-1.amazonaws.com/singularity/cohesiv/api:master"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        args:
        - "-addr=:8000"
        - "-tag-directory-addr=$(TAG_SVC_ADDR)"
        env:
        - name: SECRET_AUTH_JWT
          value: fgL8y7-ABYLZyudHBxwUXQaNsNdzJtfYjsUw_cBefJQj8s8G9s1ZWJDmNmmgG1qy
        - name: TAG_SVC_ADDR
          valueFrom:
            configMapKeyRef:
              name: hosts
              key: tagdirectory
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 256Mi
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8000
      # [END containers]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tagdirectory-deployment
spec:
  revisionHistoryLimit: 5
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: tagdirectory
    spec:
      containers:
      - image: "750213922035.dkr.ecr.us-east-1.amazonaws.com/singularity/cohesiv/tagdirectory:master"
        name: tagdirectory
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        args:
        - "-addr=:8002"
        env:
        - name: DB_CONNECTION_STRING
          value: postgres://dev:1mm3rs10n@cohesiv-development.cdss37tgqbbl.us-east-1.rds.amazonaws.com:5432/cohesiv
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 256Mi
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8002