apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-local
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP
    nodePort: 32000
    port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: tagdirectory
spec:
  type: ClusterIP
  selector:
    app: tagdirectory
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8002
